[pytest]
# Pytest Konfiguration für vtb-verein

python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Testverzeichnisse
testpaths = vtb_verein/tests

# Ausgabeformat
addopts = -v --tb=short

# Warnungen
filterwarnings =
    error
    ignore::DeprecationWarning
